import { AppUser, TrustedContact, SafePhrase, EscalationStep, GuardModeSession } from '../types'

export const mockUser: AppUser = {
  id: 'user-001',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  phoneNumber: '+1 (555) 123-4567',
  trustedContacts: [
    {
      id: 'contact-001',
      name: 'Sarah Mitchell',
      phoneNumber: '+1 (555) 987-6543',
      email: 'sarah@example.com',
      priority: 'high',
      status: 'connected',
      receivesAlerts: { low: true, medium: true, urgent: true },
    },
    {
      id: 'contact-002',
      name: 'James Chen',
      phoneNumber: '+1 (555) 456-7890',
      email: 'james@example.com',
      priority: 'high',
      status: 'connected',
      receivesAlerts: { low: false, medium: true, urgent: true },
    },
    {
      id: 'contact-003',
      name: 'Emma Rodriguez',
      phoneNumber: '+1 (555) 234-5678',
      priority: 'medium',
      status: 'pending',
      receivesAlerts: { low: false, medium: true, urgent: true },
    },
  ],
  safePhrases: [
    {
      id: 'phrase-001',
      phrase: 'The weather was nice today',
      alternatives: ['It was a beautiful day', 'Nice weather we had'],
      alertLevel: 'low',
      recipients: ['contact-001'],
      actions: [{ type: 'call', enabled: true }],
      customMessage: 'Can you call me when you get a chance?',
      isActive: true,
    },
    {
      id: 'phrase-002',
      phrase: 'I got a flat tyre',
      alternatives: ['Had a puncture', 'Got a flat'],
      alertLevel: 'medium',
      recipients: ['contact-001', 'contact-002'],
      actions: [
        { type: 'location', enabled: true },
        { type: 'message', enabled: true },
      ],
      customMessage: 'I might need some help',
      isActive: true,
    },
    {
      id: 'phrase-003',
      phrase: 'Can you remember to feed the dog',
      alternatives: ['Did you feed the dog', 'Feed the dog please'],
      alertLevel: 'urgent',
      recipients: ['contact-001', 'contact-002'],
      actions: [
        { type: 'location', enabled: true },
        { type: 'escalation', enabled: true },
        { type: 'timeline', enabled: true },
      ],
      customMessage: 'I need immediate assistance',
      isActive: true,
    },
  ],
  escalationPlan: [
    {
      id: 'step-001',
      order: 1,
      action: 'notify',
      contacts: ['contact-001'],
      delaySeconds: 0,
      description: 'Notify Sarah and request a call',
    },
    {
      id: 'step-002',
      order: 2,
      action: 'escalate',
      contacts: ['contact-002'],
      delaySeconds: 120,
      description: 'If not acknowledged, notify James',
    },
    {
      id: 'step-003',
      order: 3,
      action: 'location',
      delaySeconds: 240,
      description: 'Share live location with full Trusted Circle',
    },
  ],
  sessions: [],
  permissions: {
    microphone: true,
    location: true,
    notifications: true,
    backgroundActivity: true,
    motion: false,
  },
  privacySettings: {
    dataRetention: '3months',
    sessionHistory: true,
    locationHistory: true,
    deleteOnLogout: false,
  },
}

export const mockIncomingAlert = {
  id: 'alert-001',
  userId: 'user-001',
  userName: 'Michael Torres',
  alertLevel: 'medium' as const,
  customMessage: 'I got a flat tyre',
  currentLocation: { lat: 37.7749, lng: -122.4194 },
  batteryLevel: 65,
  lastLocationUpdate: new Date(Date.now() - 5 * 60000),
  timestamp: new Date(),
  sessionTimeline: [
    {
      id: 'event-001',
      timestamp: new Date(Date.now() - 15 * 60000),
      type: 'phrase-detected' as const,
      level: 'medium' as const,
      message: 'Sotto Mode activated',
      recipients: [],
      acknowledged: false,
    },
    {
      id: 'event-002',
      timestamp: new Date(Date.now() - 10 * 60000),
      type: 'phrase-detected' as const,
      level: 'medium' as const,
      message: 'Sotto Phrase detected: "I got a flat tyre"',
      recipients: ['contact-001'],
      acknowledged: false,
    },
  ],
}
